task: convert_rosbag2_to_non_annotated_t4
description:
  scene: ""
conversion:
  input_base: ./data/rosbag2
  output_base: ./data/non_annotated_t4_format
  world_frame_id: "base_link"
  start_timestamp_sec: 0 # Enter here if there is a timestamp for the start time. If not used, enter 0.
  skip_timestamp: 0.5 # Do not load data for the first point cloud timestamp for skip_timestamp seconds.
  num_load_frames: 0 # Maximum number of frames to save as t4 data. Set to 0 to automatically set it based on the number of lidar topics.
  accept_frame_drop: true # If true, the conversion will continue even if the LiDAR frame is dropped.
  undistort_image: true # If true, the camera image will be undistorted.
  with_ins: true            # whether to use INS messages as a ego state instead of `/tf`
  with_vehicle_status: false # whether to generate `vehicle_state.json`
  # The following configuration is generally not modified unless there are changes to the vehicle sensor configuration.
  max_camera_jitter_sec: 0.005
  lidar_latency_sec: 0.005
  system_scan_period_sec: 0.05
  lidar_sensor:
    topic: /sensing/lidar/concatenated/pointcloud
    channel: LIDAR_CONCAT
  camera_sensors: #  Keep the same order as each camera exposure timing
    - topic: /sensing/camera/camera0/image_raw/compressed
      channel: CAM_FRONT_NARROW
      delay_msec: 16.0
    - topic: /sensing/camera/camera1/image_raw/compressed
      channel: CAM_FRONT_WIDE
      delay_msec: 16.0
    - topic: /sensing/camera/camera2/image_raw/compressed
      channel: CAM_FRONT_RIGHT
      delay_msec: -9.0
    - topic: /sensing/camera/camera3/image_raw/compressed
      channel: CAM_BACK_RIGHT
      delay_msec: -59.0
    - topic: /sensing/camera/camera4/image_raw/compressed
      channel: CAM_BACK_NARROW
      delay_msec: -34.0
    - topic: /sensing/camera/camera5/image_raw/compressed
      channel: CAM_BACK_WIDE
      delay_msec: -84.0
    - topic: /sensing/camera/camera6/image_raw/compressed
      channel: CAM_BACK_LEFT
      delay_msec: -59.0
    - topic: /sensing/camera/camera7/image_raw/compressed
      channel: CAM_FRONT_LEFT
      delay_msec: -59.0
