task: convert_rosbag2_to_non_annotated_t4
description:
  scene: ""
conversion:
  input_base: ./data/rosbag2
  output_base: ./data/non_annotated_t4_format
  world_frame_id: "map"
  start_timestamp_sec: 0 # Enter here if there is a timestamp for the start time. If not used, enter 0.
  skip_timestamp: 2.0 # Do not load data for the first point cloud timestamp for skip_timestamp seconds.
  num_load_frames: 0 # Maximum number of frames to save as t4 data. Set to 0 to automatically set it based on the number of lidar topics.
  accept_frame_drop: False # If true, the conversion will continue even if the LiDAR frame is dropped.
  with_ins: true            # whether to use INS messages as a ego state instead of `/tf`
  with_vehicle_status: true # whether to generate `vehicle_state.json`
  # The following configuration is generally not modified unless there are changes to the vehicle sensor configuration.
  lidar_sensor:
    topic: /sensing/lidar/concatenated/pointcloud
    channel: LIDAR_CONCAT
  camera_sensors: #  Keep the same order as each camera exposure timing
    - topic: /sensing/camera/camera3/image_raw/compressed
      channel: CAM_BACK_LEFT
      delay_msec: 48.33
    - topic: /sensing/camera/camera2/image_raw/compressed
      channel: CAM_FRONT_LEFT
      delay_msec: 65.0
    - topic: /sensing/camera/camera0/image_raw/compressed
      channel: CAM_FRONT
      delay_msec: 81.67
    - topic: /sensing/camera/camera4/image_raw/compressed
      channel: CAM_FRONT_RIGHT
      delay_msec: 98.33
    - topic: /sensing/camera/camera5/image_raw/compressed
      channel: CAM_BACK_RIGHT
      delay_msec: 115.0
    - topic: /sensing/camera/camera1/image_raw/compressed
      channel: CAM_BACK
      delay_msec: 131.67
