task: convert_camera_only_rosbag2_to_non_annotated_t4
description:
  scene: ""
conversion:
  input_base: ./data/camera_only_rosbag2
  output_base: ./data/non_annotated_t4_format
  skip_timestamp_sec: 0 # Enter here if there is a timestamp for the start time. If not used, enter 0.
  skip_timestamp: 2.0 # Do not load data for the first point cloud timestamp for skip_timestamp seconds
  num_load_frames: 0 # Maximum number of frames to save as t4 data. Set to 0 to automatically set it based on the number of lidar topics.
  system_scan_period_sec: 0.005
  max_camera_jitter_sec: 0.005
  camera_sensors:
    - topic: /sensing/camera/camera0/image_rect_color
      channel: CAM_FRONT
      delay_msec: 81.67
    - topic: /sensing/camera/camera6/image_raw
      channel: CAM_TRAFFIC_LIGHT_FAR
      delay_msec: 100
    - topic: /sensing/camera/camera7/image_raw
      channel: CAM_TRAFFIC_LIGHT_NEAR
      delay_msec: 100
